GET http://127.0.0.1:4000/mascotas/buscar HTTP/1.1

###
GET http://127.0.0.1:4000/mascotas/buscarId/2 HTTP/1.1

###
POST http://127.0.0.1:4000/mascotas/crear HTTP/1.1
Content-type: application/json

{
    "name": "Luna",
    "species": "Gato",
    "breed": "Siamés",
    "age": 3,
    "description": "Gata tranquila y cariñosa, ideal para interiores.",
    "status": "adopted",
    "gender": "femenino",
    "size": "pequeño",
    "weight": 4.2,
    "entry_date": "2024-08-20",
    "vaccinated": true,
    "neutered": false,
    "medical_conditions": "Alergia leve",
    "available_for_adoption": false
}




###
PUT http://127.0.0.1:4000/mascotas/actualizar/2 HTTP/1.1
Content-type: application/json

{
    "name": "Max",
    "species": "Conejo",
    "breed": "Enano",
    "age": 2,
    "description": "Conejo enano, muy activo y curioso.",
    "status": "available",
    "gender": "masculino",
    "size": "pequeño",
    "weight": 1.8,
    "entry_date": "2024-09-01",
    "vaccinated": false,
    "neutered": false,
    "medical_conditions": "Problema dental recurrente",
    "available_for_adoption": true
}


###
DELETE http://127.0.0.1:4000/mascotas/eliminar/2 HTTP/1.1